name: Node.js CI

on:
  push:
    branches: [ "main" ]
    paths: [
      'web/**',
      '.github/workflows/web.yml'
    ]
  pull_request:
    branches: [ "main" ]
    paths: [
      'web/**',
      '.github/workflows/web.yml'
    ]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'
        cache-dependency-path: './web/package-lock.json'
    - run: npm ci
    - run: npm run qa
    - run: npm run build --if-present
    - run: npm test
